[package]
name = "vault"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
generic_witness = { local = "test_packages/generic_witness", modes = ["test"] }
